"""SmeRepositoryPort — persists and retrieves SmeTemplate config."""
from __future__ import annotations

from typing import Protocol

from sentinel_domain.sme import SmeTemplate


class SmeRepositoryPort(Protocol):
    async def list_templates(self) -> list[SmeTemplate]: ...
    async def get_template(self, template_id: str) -> SmeTemplate | None: ...
    async def save_template(self, template: SmeTemplate) -> None: ...
    async def delete_template(self, template_id: str) -> None: ...
